### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by whyour** [atian25/alfred-plugin-projj#1]
```js
{ Error: Command failed: alfred-link
Error: Alfred preferences not found at location /Users/wangpeng/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist
    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-plugin-projj/node_modules/resolve-alfred-prefs/index.js:15:10)


    at makeError (/usr/local/lib/node_modules/alfred-plugin-projj/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/alfred-plugin-projj/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  stdout: '',
  stderr:
   'Error: Alfred preferences not found at location /Users/wangpeng/Library/Preferences/com.runningwithcrayons.Alfred-Preferences-3.plist\n    at pathExists.then.exists (/usr/local/lib/node_modules/alfred-plugin-projj/node_modules/resolve-alfred-prefs/index.js:15:10)\n',
  failed: true,
  signal: null,
  cmd: 'alfred-link',
  timedOut: false,
  killed: false }
```

**Comment by atian25** [comment]
似乎是你的 Alfred 安装的问题。

你可以自己把应用 link 或复制到这里

![image](https://user-images.githubusercontent.com/227713/54656427-8c73e700-4b00-11e9-8dd4-8e9034e56c80.png)
